SELECT PARTS.pid FROM PARTS WHERE PARTS.pid IN  (SELECT CATALOG.pid FROM CATALOG WHERE cost < 10);
SELECT PARTS.pname FROM PARTS WHERE PARTS.pid IN  (SELECT CATALOG.pid FROM CATALOG WHERE cost < 10);
SELECT address FROM SUPPLIERS WHERE SUPPLIERS.sid IN (SELECT catalog.sid FROM CATALOG WHERE catalog.pid = (SELECT parts.pid FROM Parts WHERE pname = 'Fire Hydrant Cap'));
SELECT SNAME FROM SUPPLIERS WHERE SID = ( SELECT SID FROM CATALOG WHERE PID = ( SELECT pid from PARTS WHERE color = 'Green'));
SELECT sname, pname FROM SUPPLIERS, PARTS, CATALOG WHERE PARTS.pid = catalog.pid AND CATALOG.SID = SUPPLIERS.sid GROUP BY sname, pname;
